<?php

namespace Test\Ease\TWB5;

use Ease\TWB5\Badge;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-02-01 at 12:09:00.
 */
class BadgeTest extends \Test\Ease\Html\DivTagTest
{

    /**
     * @var Badge
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Badge();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }
}
