<?php

namespace Test\Ease\TWB5;

use Ease\TWB5\Card;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-01-31 at 11:50:21.
 */
class CardTest extends \Test\Ease\Html\DivTagTest
{

    /**
     * @var Card
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Card();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }
}
