<?php

namespace Test\Ease\TWB5;

use Ease\TWB5\Container;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-12-30 at 18:33:39.
 */
class ContainerTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Container
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Container();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {

    }
}