<?php

namespace Test\Ease\TWB5;

use Ease\TWB5\InputGroup;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-01-31 at 12:33:22.
 */
class InputGroupTest extends \PHPUnit\Framework\TestCase
{

    /**
     * @var InputGroup
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new InputGroup();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }
}
