<?php

declare(strict_types=1);

/**
 * This file is part of the EaseTWB5 package
 *
 * https://github.com/VitexSoftware/php-ease-twbootstrap5/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\Ease\TWB5;

use Ease\TWB5\NavItemDropDown;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-12-30 at 18:33:39.
 */
class NavItemDropDownTest extends \PHPUnit\Framework\TestCase
{
    protected NavItemDropDown $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new NavItemDropDown();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \Ease\TWB5\NavItemDropDown::handle
     *
     * @todo   Implement testhandle().
     */
    public function testhandle(): void
    {
        $this->assertEquals('', $this->object->handle());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Ease\TWB5\NavItemDropDown::addDropdownItem
     *
     * @todo   Implement testaddDropdownItem().
     */
    public function testaddDropdownItem(): void
    {
        $this->assertEquals('', $this->object->addDropdownItem());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Ease\TWB5\NavItemDropDown::finalize
     *
     * @todo   Implement testfinalize().
     */
    public function testfinalize(): void
    {
        $this->assertEquals('', $this->object->finalize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
