<?php

declare(strict_types=1);

/**
 * This file is part of the EaseTWB5 package
 *
 * https://github.com/VitexSoftware/php-ease-twbootstrap5/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\Ease\TWB5;

use Ease\TWB5\Panel;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-01-31 at 12:00:41.
 */
class PanelTest extends CardTest
{
    protected Panel $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Panel();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \Ease\TWB5\Panel::addItem
     *
     * @todo   Implement testaddItem().
     */
    public function testaddItem(): void
    {
        $this->assertEquals('', $this->object->addItem());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Ease\TWB5\Panel::finalize
     *
     * @todo   Implement testfinalize().
     */
    public function testfinalize(): void
    {
        $this->assertEquals('', $this->object->finalize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
