<?php

namespace Test\Ease\TWB5;

use Ease\TWB5\Part;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-12-30 at 18:33:39.
 */
class PartTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Part
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Part();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {

    }

    /**
     * @covers Ease\TWB5\Part::twBootstrapize
     * @todo   Implement testtwBootstrapize().
     */
    public function testtwBootstrapize()
    {
        $this->assertEquals('', $this->object->twBootstrapize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}