<?php

namespace Test\Ease\TWB5;

use Ease\TWB5\Row;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-01-31 at 11:13:35.
 */
class RowTest extends \PHPUnit\Framework\TestCase
{

    /**
     * @var Row
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Row();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers Ease\TWB5\Row::addColumn
     * @todo   Implement testaddColumn().
     */
    public function testaddColumn()
    {
        $this->assertEquals('', $this->object->addColumn());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
