<?php

namespace Test\Ease\TWB5;

use Ease\TWB5\SubmitButton;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-01-31 at 11:57:06.
 */
class SubmitButtonTest extends \Test\Ease\Html\ButtonTagTest
{

    /**
     * @var SubmitButton
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new SubmitButton();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }
}
