<?php

namespace Test\Ease\TWB5;

use Ease\TWB5\WebPage;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-12-30 at 18:33:40.
 */
class WebPageTest extends \Test\Ease\WebPageTest
{
    /**
     * @var WebPage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new WebPage();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {

    }

    /**
     * @covers Ease\TWB5\WebPage::addToHeader
     * @todo   Implement testaddToHeader().
     */
    public function testaddToHeader()
    {
        $this->assertEquals('', $this->object->addToHeader());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Ease\TWB5\WebPage::addToMain
     * @todo   Implement testaddToMain().
     */
    public function testaddToMain()
    {
        $this->assertEquals('', $this->object->addToMain());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Ease\TWB5\WebPage::addToFooter
     * @todo   Implement testaddToFooter().
     */
    public function testaddToFooter()
    {
        $this->assertEquals('', $this->object->addToFooter());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Ease\TWB5\WebPage::finalize
     * @todo   Implement testfinalize().
     */
    public function testfinalize()
    {
        $this->assertEquals('', $this->object->finalize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}